version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - marketmate-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=marketmate
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    ports:
      - "27017:27017"
    networks:
      - marketmate-net

networks:
  marketmate-net:
    driver: bridge
